
//CNMCOMPLEX = CinemaComplex
export const FETCH_ALL_CNMCOMPLEX_REQUEST = 'FETCH_ALL_CNMCOMPLEX_REQUEST'
export const FETCH_ALL_CNMCOMPLEX_SUCCESS = 'FETCH_ALL_CNMCOMPLEX_SUCCESS'
export const FETCH_ALL_CNMCOMPLEX_FAIL = 'FETCH_ALL_CNMCOMPLEX_FAIL'