export const FETCH_ALL_MOVIE_REQUEST = 'FETCH_ALL_MOVIE_REQUEST'
export const FETCH_ALL_MOVIE_SUCCESS = 'FETCH_ALL_MOVIE_SUCCESS'
export const FETCH_ALL_MOVIE_FAIL = 'FETCH_ALL_MOVIE_FAIL'
//Fetch Showtime by Movie
export const FETCH_SHOWTIME_BY_MOVIE_REQUEST = 'FETCH_SHOWTIME_BY_MOVIE_REQUEST'
export const FETCH_SHOWTIME_BY_MOVIE_SUCCESS = 'FETCH_SHOWTIME_BY_MOVIE_SUCCESS'
export const FETCH_SHOWTIME_BY_MOVIE_FAIL = 'FETCH_SHOWTIME_BY_MOVIE_FAIL'
//Lấy data cụm rạp chiếu phim  khi click chọn rạp
export const GET_CINEMA_COMPLEX_DATA = 'GET_CINEMA_COMPLEX_DATA'